import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/app/components/ThemeProvider";
import Navbar from "./components/Navbar";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        // suppressHydrationWarning is required for next-themes
        <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap everything in the ThemeProvider */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <div
                className="min-h-screen bg-white dark:bg-black text-black dark:text-white transition-colors duration-200">
                {/* Navbar is now inside the provider, so it can toggle the theme */}
                <Navbar/>

                {/* Main content area */}
                <div className="max-w-2xl mx-auto border-x border-gray-100 dark:border-gray-800 min-h-screen">
                    {children}
                </div>
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}